# Generated by Django 4.1 on 2022-08-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('alternativa1', models.CharField(max_length=200, null=True)),
                ('alternativa2', models.CharField(max_length=200, null=True)),
                ('alternativa3', models.CharField(max_length=200, null=True)),
                ('alternativa4', models.CharField(max_length=200, null=True)),
                ('resposta', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
